version: '3.8'
name: spring-boot-explore
services:
  postgres:
    container_name: postgres
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: references
  application:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
      - "7080:7080"
    depends_on:
      - postgres